version: '3.8'

services:
  auth-service:
    build: ./auth-service
    ports:
      - "5000:5000"
    networks:
      - app-network
    environment:
      - DB_HOST=db
      - DB_PORT=3306

  user-service:
    build: ./user-service
    ports:
      - "5001:5001"
    networks:
      - app-network
    environment:
      - DB_HOST=db
      - DB_PORT=3306

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appdb
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:

volumes:
  db-data:
